# Generated by Django 3.2.4 on 2021-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='User_type',
            field=models.CharField(choices=[('BU', 'Buyer'), ('SL', 'Seller')], default='BU', max_length=2),
        ),
    ]
