# Generated by Django 3.2.4 on 2021-06-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concrete', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Concrete_pump', models.CharField(choices=[('MP', 'Mobile pump'), ('SP', 'Stationary pump'), ('NO', 'No pump')], default='NO', max_length=2)),
                ('Address', models.CharField(max_length=100)),
                ('Pour_date', models.DateTimeField()),
                ('Customer_type', models.CharField(max_length=20)),
                ('Payment', models.CharField(max_length=20)),
                ('Order_status', models.CharField(max_length=20)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Concrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concrete.concrete')),
            ],
        ),
    ]
