# Generated by Django 3.2.4 on 2021-06-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Customer_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payment',
        ),
    ]
